#-- Source Files -----------------------------------------------

source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/theme.conf

#-- General ----------------------------------------------------
general {
	border_size = $hypr_border_size
	gaps_in = $hypr_gaps_in
	gaps_out = $hypr_gaps_out
	col.active_border = $active_border_col
	col.inactive_border = $inactive_border_col
	layout = dwindle
}


#-- Workspace Gestures -----------------------------------------
gestures {
	workspace_swipe_distance = 300
	workspace_swipe_invert = true
	workspace_swipe_min_speed_to_force = 30
	workspace_swipe_cancel_ratio = 0.5
	workspace_swipe_create_new = true
	workspace_swipe_forever = false
}

gesture = 3, horizontal, workspace

#-- Miscellaneous ----------------------------------------------
misc {
	vfr = on
	vrr = 1
	mouse_move_enables_dpms = false
	always_follow_on_dnd = true
	disable_splash_rendering = true
	disable_hyprland_logo = true
	layers_hog_keyboard_focus = true
	animate_manual_resizes = false
	disable_autoreload = false
	enable_swallow = false
	swallow_regex = 
	focus_on_activate = true
}

#-- Binds ------------------------------------------------------
binds {
	pass_mouse_when_bound = false
	scroll_event_delay = 300
	workspace_back_and_forth = false
	allow_workspace_cycles = false
}

#-- Debug (Only for developers) --------------------------------
debug {
	overlay = false
	damage_blink = false
	disable_logs = false
	disable_time = true
	damage_tracking = 2
}

#-- Output -----------------------------------------------------
monitor = ,preferred,auto,1

wallpaper = , /home/avery/Pictures/Wallpapers/wallpaper.png

splash = false


$term        = kitty
$lockscreen  = hyprlock
$colorpicker = ~/.config/hypr/scripts/colorpicker
$files       = thunar
$editor      = code
$browser     = firefox

$rofi_launcher    = ~/.config/hypr/scripts/menu.sh drun
$rofi_runner      = ~/.config/hypr/scripts/menu.sh run
$rofi_powermenu   = ~/.config/hypr/scripts/pmenu.sh

$volumemute = swayosd-client --output-volume mute-toggle
$volumedown = swayosd-client --output-volume lower
$volumeup = swayosd-client --output-volume raise  

$brightnessdown = swayosd-client --brightness lower
$brightnessup = swayosd-client --brightness raise

$screenshot = ~/.config/hypr/scripts/screenshot.sh

source = ~/.config/hypr/config/keybinds.conf