#-- Exec -------------------------------------------------------
exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec = ~/.config/hypr/scripts/waybar_peek.py
exec = swayosd-server
exec-once = systemctl --user start hyprpolkitagent
