source = ~/.config/hypr/macchiato.conf

# Elements
$hypr_border_size = 2
$hypr_gaps_in = 8
$hypr_gaps_out = 8
$hypr_rounding = 0

# Colors
$active_border_col = $blue
$inactive_border_col = $text

#-- Decoration -------------------------------------------------
decoration {
	rounding = 0
	active_opacity = 1.0
	inactive_opacity = 1.0
	fullscreen_opacity = 1.0
	dim_inactive = true
	dim_strength = 0.2
}

#-- Animations -------------------------------------------------
animations {
	enabled = true
	animation = windowsIn,1,2,default,popin
	animation = windowsOut,1,2,default,popin
	animation = windowsMove,1,2,default,slide
	animation = fadeIn,1,0.5,default
	animation = fadeOut,1,0.5,default
	animation = fadeSwitch,1,0.5,default
	animation = fadeDim,1,0.5,default
	animation = border,1,2,default
	animation = workspaces,1,5,default,slide
}

#-- Layout : Dwindle -------------------------------------------
dwindle {
	pseudotile = false
	force_split = 0
	preserve_split = false
	special_scale_factor = 0.8
	split_width_multiplier = 1.0
#	no_gaps_when_only = false
	use_active_for_splits = true
}

$notifycmd = notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low
bind = SUPER, G, togglegroup
bind = SUPER, G, exec, $notifycmd 'Toggled Group Mode'
bind = SUPER, H, changegroupactive, b
bind = SUPER, L, changegroupactive, f

#-- Layout : Master --------------------------------------------
master {
	special_scale_factor = 0.8
	new_on_top = false
	orientation = left
}

#-- Window Rules -----------------------------------------------
windowrule {
    name = float-dialogs
    match:class = ^(yad|nm-connection-editor|pavucontrolk|)$
    float = on
}

windowrule {
    name = float-settings
    match:class = ^(xfce-polkit|kvantummanager|qt5ct)$
    float = on
}


windowrule {
    name = float-file-progress
    match:title = ^File Operation Progress$
    float = on
}

windowrule {
    name = float-confirm-replace
    match:title = ^Confirm to replace files$
    float = on
}

